# permissions for end users to view providerinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: providerinstance-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - providerinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - providerinstances/status
  verbs:
  - get
