# permissions for end users to edit providerinventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: providerinventory-editor-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - providerinventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - providerinventories/status
  verbs:
  - get
