# permissions for end users to view providerinventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: providerinventory-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com.provider.com
  resources:
  - providerinventories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com.provider.com
  resources:
  - providerinventories/status
  verbs:
  - get
