# permissions for end users to view providerconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: providerconnection-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - providerconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - providerconnections/status
  verbs:
  - get
